name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # 1. Setup QEMU & Buildx
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 2. Prevent "Illegal Instruction" errors
      - name: Install QEMU Handlers
        run: |
          docker run --rm --privileged tonistiigi/binfmt --install all

      # 3. AUTHENTICATION
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Create lowercase variable for the image paths
      - name: Set Repo Owner Env
        run: |
          echo "REPO_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # 4. Build & Push Backend
      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./movie-planner-backend
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            QEMU_CPU=max
          tags: ghcr.io/${{ env.REPO_LOWER }}/movie-backend:latest

      # 5. Build & Push Frontend
      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./movie-planner-frontend
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            REACT_APP_API_BASE_URL=${{ secrets.REACT_APP_API_BASE_URL }}
            QEMU_CPU=max
          tags: ghcr.io/${{ env.REPO_LOWER }}/movie-frontend:latest

  # 6. Cleanup Job (Prunes old images)
  cleanup:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    permissions:
      packages: write
    steps:
      - name: Delete old versions
        uses: actions/delete-package-versions@v4
        with: 
          package-name: 'movie-backend'
          package-type: 'container'
          min-versions-to-keep: 3
      - name: Delete old versions
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'movie-frontend'
          package-type: 'container'
          min-versions-to-keep: 3
